１カ月移動平均線 = 
-- 4 Weeks
var interval = -28
RETURN
    IF (
        NOT ISBLANK(SUM('WHO-COVID-19-candle'[Close])),
        DIVIDE(
            CALCULATE(
                SUM('WHO-COVID-19-candle'[Close]),
                DATESINPERIOD(
                    'WHO-COVID-19-candle'[date],
                    LASTDATE('WHO-COVID-19-candle'[date]),
                    interval,
                    DAY
                )
            ),
            CALCULATE(
                COUNTA('WHO-COVID-19-candle'[Close]),
                DATESINPERIOD(
                    'WHO-COVID-19-candle'[date],
                    LASTDATE('WHO-COVID-19-candle'[date]),
                    interval,
                    DAY
                )
            )
        )
    )